name: İŞKUR Bot

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  check-jobs:
    runs-on: ubuntu-latest

    steps:
      - name: Kodu indir
        uses: actions/checkout@v4

      - name: Python kur
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Paketleri kur
        run: |
          pip install playwright requests python-dotenv
          python -m playwright install --with-deps chromium

      - name: Botu çalıştır
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python bot.py

      - name: İlan hafızasını kaydet
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add ilanlar.json

          if git diff --cached --quiet; then
            echo "Yeni kayıt yok."
          else
            git commit -m "İlan hafızasını güncelle"
            git push
          fi
